In [18]:
import re
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv('20250423_scraped_reviews.csv')

In [4]:
df.head()

,Hotel_Name,Hotel_Address,Average_Score,Review_Date,Reviewer_Score,Positive_Review,Negative_Review,Tags
0,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-02-07,9.0,away from the busy streets of pai 12 minute dr...,it was quite cold in the night in the room,"['Leisure trip', 'Solo traveler', 'Holiday Hom..."
1,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-02-06,9.0,relaxing stay walking distance to hot springs ...,cold shower not freezing it didnt bother me to...,"['Leisure trip', 'Couple', 'Tent', 'Stayed 2 n..."
2,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-01-23,10.0,everything has been good,the only problem is that it gets quite cold at...,"['Leisure trip', 'Solo traveler', 'Double Room..."
3,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-01-29,7.0,its in a beautiful country setting and the sta...,the shower water was cold only yep there was n...,"['Leisure trip', 'Solo traveler', 'Tent', 'Sta..."
4,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-01-19,7.0,it have the vibe of pai and its very relaxing ...,its very cold in the evening \nand without a b...,"['Leisure trip', 'Solo traveler', 'Holiday Hom..."

In [5]:
df.describe()

       Average_Score  Reviewer_Score
count   51871.000000    51871.000000
mean        8.431686        8.012011
std         1.181043        2.456718
min         1.000000        1.000000
25%         7.900000        7.000000
50%         8.700000        9.000000
75%         9.300000       10.000000
max        10.000000       10.000000

## Obtain top-n frequency terms

In [6]:
# Prepare text columns
pos_text = df['Positive_Review'].fillna('').str.lower()
neg_text = df['Negative_Review'].fillna('').str.lower()

In [7]:
# Vectorize positive reviews
vec_pos = CountVectorizer(stop_words='english', min_df=5)

pos_mat = vec_pos.fit_transform(pos_text)
pos_counts = pos_mat.sum(axis=0).A1
pos_series = pd.Series(pos_counts, index=vec_pos.get_feature_names_out())

top_pos = pos_series.sort_values(ascending=False).head(25)
top_pos = top_pos.to_dict()

In [8]:
# Vectorize negative reviews
vec_neg = CountVectorizer(stop_words='english', min_df=5)

neg_mat = vec_neg.fit_transform(neg_text)
neg_counts = neg_mat.sum(axis=0).A1
neg_series = pd.Series(neg_counts, index=vec_neg.get_feature_names_out())

top_neg = neg_series.sort_values(ascending=False).head(25)
top_neg = top_neg.to_dict()

In [9]:
# Output
print("Top 25 Positive Terms:\n", top_pos)
print("\nTop 25 Negative Terms:\n", top_neg)

Top 25 Positive Terms:
 {'location': 17508, 'clean': 14736, 'good': 11613, 'great': 10827, 'room': 9194, 'nice': 8847, 'comfortable': 8254, 'stay': 7813, 'staff': 7718, 'place': 5984, 'apartment': 5636, 'friendly': 5402, 'helpful': 4867, 'host': 4370, 'close': 4275, 'really': 4245, 'property': 4133, 'lovely': 4105, 'bed': 3995, 'hotel': 3796, 'breakfast': 3789, 'spacious': 3707, 'perfect': 3662, 'beautiful': 3370, 'quiet': 3318}

Top 25 Negative Terms:
 {'room': 10197, 'didnt': 4588, 'bathroom': 4195, 'like': 4014, 'bit': 3662, 'bed': 3660, 'water': 3660, 'shower': 3575, 'stay': 3487, 'night': 3411, 'good': 3193, 'just': 3101, 'small': 2999, 'hotel': 2949, 'property': 2825, 'door': 2817, 'place': 2787, 'apartment': 2772, 'little': 2446, 'time': 2446, 'did': 2420, 'wasnt': 2387, 'clean': 2272, 'kitchen': 2226, 'really': 2200}

## Identify trend in themes

In [13]:
# Parse dates
df['Review_Date'] = pd.to_datetime(df['Review_Date'], errors='coerce')
df = df.dropna(subset=['Review_Date'])  # drop any bad dates
df['Month'] = df['Review_Date'].dt.to_period('M')

In [16]:
def label_sentiment(score: int) -> str:
    if score >= 7:
        return 'Positive'
    elif score <= 4:
        return 'Negative'
    else:
        return 'Neutral'

df['Sentiment'] = df['Reviewer_Score'].apply(label_sentiment)

In [19]:
# Helper to clean text
def clean_text(txt: str) -> str:
    if pd.isna(txt):
        return ""
    return re.sub(r'[^\w\s]', '', txt.lower())

df['PosClean'] = df['Positive_Review'].apply(clean_text)
df['NegClean'] = df['Negative_Review'].apply(clean_text)
df.head()

,Hotel_Name,Hotel_Address,Average_Score,Review_Date,Reviewer_Score,Positive_Review,Negative_Review,Tags,Month,Sentiment,PosClean,NegClean
0,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-02-07,9.0,away from the busy streets of pai 12 minute dr...,it was quite cold in the night in the room,"['Leisure trip', 'Solo traveler', 'Holiday Hom...",2025-02,Positive,away from the busy streets of pai 12 minute dr...,it was quite cold in the night in the room
1,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-02-06,9.0,relaxing stay walking distance to hot springs ...,cold shower not freezing it didnt bother me to...,"['Leisure trip', 'Couple', 'Tent', 'Stayed 2 n...",2025-02,Positive,relaxing stay walking distance to hot springs ...,cold shower not freezing it didnt bother me to...
2,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-01-23,10.0,everything has been good,the only problem is that it gets quite cold at...,"['Leisure trip', 'Solo traveler', 'Double Room...",2025-01,Positive,everything has been good,the only problem is that it gets quite cold at...
3,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-01-29,7.0,its in a beautiful country setting and the sta...,the shower water was cold only yep there was n...,"['Leisure trip', 'Solo traveler', 'Tent', 'Sta...",2025-01,Positive,its in a beautiful country setting and the sta...,the shower water was cold only yep there was n...
4,NichahomePai,108 10 58130 Ban Pa Fang Thailand,8.6,2025-01-19,7.0,it have the vibe of pai and its very relaxing ...,its very cold in the evening \nand without a b...,"['Leisure trip', 'Solo traveler', 'Holiday Hom...",2025-01,Positive,it have the vibe of pai and its very relaxing ...,its very cold in the evening \nand without a b...

In [21]:
# Theme to keyword mapping
themes = {
    'Location':       ["location", "area", "distance", "walk", "situated"],
    'Cleanliness':    ["clean", "dirty", "tidy", "hygiene"],
    'Staff_Service':  ["staff", "service", "helpful", "friendly", "host"],
    'Room_Comfort':   ["bed", "room", "spacious", "comfortable", "small"],
    'Noise':          ["noise", "noisy", "quiet", "loud", "sound"],
    'Food_Breakfast': ["breakfast", "food", "restaurant", "dining"],
    'WiFi':           ["wifi", "internet", "connection"],
}

# Tag each review for each theme (positive & negative)
records = []
for _, row in df.iterrows():
    month = row['Month']
    pos_text = row['PosClean']
    neg_text = row['NegClean']
    for theme, kws in themes.items():
        has_pos = any(kw in pos_text for kw in kws)
        has_neg = any(kw in neg_text for kw in kws)
        if has_pos or has_neg:
            records.append({
                'Month':      month,
                'Theme':      theme,
                'Positive':   int(has_pos),
                'Negative':   int(has_neg)
            })

theme_df = pd.DataFrame(records)
theme_df.head()

     Month           Theme  Positive  Negative
0  2025-02    Room_Comfort         0         1
1  2025-02        Location         1         1
2  2025-02   Staff_Service         1         0
3  2025-02    Room_Comfort         1         1
4  2025-02  Food_Breakfast         1         0

In [28]:
# Aggregate & compute net-sentiment
monthly = (
    theme_df
    .groupby(['Month','Theme'])[['Positive','Negative']]
    .sum()
    .reset_index()
)
monthly['Total']       = monthly['Positive'] + monthly['Negative']
monthly['NetSentiment'] = (monthly['Positive'] - monthly['Negative']) / monthly['Total']
sentiment_by_month = monthly.pivot(index='Month', columns='Theme', values='NetSentiment')
sentiment_by_month.head()

Theme,Cleanliness,Food_Breakfast,Location,Noise,Room_Comfort,Staff_Service,WiFi
Month,,,,,,,
2024-08,0.000000,NaN,-1.000000,NaN,1.000000,NaN,NaN
2024-09,0.617834,0.672727,0.675439,0.069124,0.329466,0.638752,-0.241379
2024-10,0.623327,0.523810,0.690687,0.126615,0.235782,0.619979,-0.242321
2024-11,0.529898,0.412180,0.634093,0.012658,0.139482,0.574650,-0.268765
2024-12,0.504505,0.341414,0.624704,-0.042205,0.090124,0.522489,-0.282851

In [31]:
## TRY TO LOAD THIS SENTIMENT TREND DATA SOMEWHERE